modified atomate-terraform.yml
LauPerlaza/Duck-Shop pull request #8
Opened 2024-02-24 06:03 UTC by LauPerlaza

2024-02-24 19:13 UTC, danielrive requested changes
En mi opinion es mejor tener un workflow(pipeline) diferente para terraform y otro para el build de las applicaciones, son cosas independientes de momento por lo que si yo solo quiero una nueva container images no tengo q correr terraform si solo es hacer docker build

2024-02-24 19:13 UTC, danielrive commented on .github/workflows/automate-terraform.yml
> +      - name: Build Docker Image
no es necesario correr terraform antes, con este pipeline si yo solo hago cambios en el codigo de la api se va a correr terraform tambien lo q no es necesario, anadiendo mas pasos por ejecutar sin necesidad

2024-02-24 19:13 UTC, danielrive commented on .github/workflows/automate-terraform.yml
> +          echo "::set-output name=image_uri::${{ env.ECR_REGISTRY_URI }}/my-app:${{ github.sha }}"
que es my-app ?

2024-02-24 19:13 UTC, danielrive commented on .github/workflows/automate-terraform.yml
> +          aws ecr get-login-password --region us-east-1 --profile ${{ env.AWS_PROFILE }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY_URI }}
que pasa si la region cambia?
porq usar aws profiles?  de donde se saca las credenciales?

2024-02-24 19:13 UTC, danielrive commented on .github/workflows/automate-terraform.yml
> +          echo "::set-output name=image_uri::${{ env.ECR_REGISTRY_URI }}/my-app:${{ github.sha }}"
que hace esto?

2024-02-24 19:14 UTC, danielrive commented
adicional faltaria la regla para que el workflow se dispare solo cuando se hacen modificaciones en el folder del API

2024-02-25 23:42 UTC, LauPerlaza commented on .github/workflows/automate-terraform.yml
> +          echo "::set-output name=image_uri::${{ env.ECR_REGISTRY_URI }}/my-app:${{ github.sha }}"
aquí se construye la imagen de docker, se le asigna un nombre y una etiqueta basados en el URI (del registro que cree manualmente la consola de aws y se esta pasando como una variable) y el SHA del commit de GitHub, y luego establece una variable de salida (image_uri) con el URI completo de la imagen construida

2024-02-26 00:39 UTC, LauPerlaza commented on .github/workflows/automate-terraform.yml
> +          aws ecr get-login-password --region us-east-1 --profile ${{ env.AWS_PROFILE }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY_URI }}
mm error mio, debería usar los pasos para autenticar que me da la misma consola de aws

2024-02-26 07:06 UTC, LauPerlaza commented on .github/workflows/automate-terraform.yml
> +          echo "::set-output name=image_uri::${{ env.ECR_REGISTRY_URI }}/my-app:${{ github.sha }}"
ok. cree un nuevo workflow para el build de las app

2024-02-26 07:18 UTC, LauPerlaza commented on .github/workflows/automate-terraform.yml
> +          echo "::set-output name=image_uri::${{ env.ECR_REGISTRY_URI }}/my-app:${{ github.sha }}"
cambie el nombre de la imagen que era "my-app" por "duck-shop"

2024-02-26 08:53 UTC, danielrive commented on .github/workflows/build-push.yml
> +        uses: actions/checkout@v2
creo q hay una nuve version, invesitgar sobre el checkout v3

2024-02-26 08:54 UTC, danielrive commented
no veo que este corriendo el pipeline bien

2024-02-26 15:37 UTC, LauPerlaza commented on .github/workflows/build-push.yml
> +        uses: actions/checkout@v2
hemos hablado de esto un monton y hay falta explicar algo porque no he podido hacerlo por si no recuerda

2024-02-26 15:38 UTC, LauPerlaza commented
no, el pipline no esta corriendo bien y me gustaria que revisara bien porque no se por que

2024-02-26 17:22 UTC, danielrive commented on .github/workflows/build-push.yml
> +        uses: actions/checkout@v2
https://github.com/marketplace/actions/checkout

2024-02-26 17:23 UTC, danielrive commented
el pipeline tiene una regla para q el workflow se inicie siempre y cuando hayan cambios en un folder, si no hay cambios ps no se inicia

2024-02-26 17:26 UTC, LauPerlaza commented
se inicia, se hace el build pero no se puede hacer el push a ecr

2024-02-26 17:32 UTC, danielrive commented
time out error

esta intantando hacer push a 

docker push ***.dkr.ecr.us-east-1.amazonaws.com/duck-shop-0.1/duck-shop

el repositorio creo q solo se llama  ACCOUNT:dkr.ecr.us-east-1.amazonaws.com/duck-shop-0.1

2024-02-26 21:56 UTC, danielrive approved these changes

2024-02-26 22:33 UTC, merged